### ISSUE TITLE
My Sadness の歌詞を完成させる

### ISSUE THREAD

**Issue by yuusukeyamashita** [mosquitone/songs#1]
[My Sadness の歌詞](https://github.com/mosquitone/songs/blob/master/my_sadness/lyrics.txt)を完成させる。

**Comment by chikarautsumi** [comment]
This task’s already completed

**Comment by chikarautsumi** [comment]
You are now an owner of mosquitone!

**Comment by chikarautsumi** [comment]
This task’s already completed
